apiVersion: v1
kind: Service
metadata:
  name: claudecodeui
  namespace: claudecodeui
spec:
  selector:
    app: claudecodeui
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
