apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dnsendpoint-crd.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - cloudflare-secret.yaml
  - dnsendpoints.yaml
