apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-proxmox-runtime
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          # Empty containers list required to pass validation (crossplane/crossplane#5442)
          containers: []
          nodeSelector:
            kubernetes.io/hostname: k3s-vm-pumped-piglet-gpu
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
