apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# NOTE: Don't set namespace here - each file specifies its own namespace
# HelmRepository goes to flux-system, HelmRelease to crossplane-system
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - proxmox-ssh-key.sops.yaml
  # TODO: Move to separate Flux Kustomization with dependency on Crossplane HelmRelease
  # These require Crossplane Provider CRD which is installed by crossplane HelmRelease
  # - provider-proxmox.yaml
  # - proxmox-secret.yaml
  # - provider-config.yaml
