apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secrets/ghcr-creds.sops.yaml
- image-automation-pve-nut.yaml
- image-automation-proxmox-provisioner.yaml
- image-automation-frigate-health-checker.yaml
- image-automation-ollama-scripts.yaml
