apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigate-api
  namespace: frigate
spec:
  entryPoints:
    - frigate-api
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigate-rtsp
  namespace: frigate
spec:
  entryPoints:
    - frigate-rtsp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: 8554
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frigate-webrtc-tcp
  namespace: frigate
spec:
  entryPoints:
    - frigate-webrtc-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: frigate
          port: 8555
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: frigate-webrtc-udp
  namespace: frigate
spec:
  entryPoints:
    - frigate-webrtc-udp
  routes:
    - services:
        - name: frigate
          port: 8555
