apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-test
resources:
  - namespace.yaml
  - crucible-storage-class.yaml
  - helmrelease.yaml
  - secrets/grafana-admin.sops.yaml
