apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frigate-ip-webhook
  namespace: frigate
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`frigate-webhook.app.home.panderosystems.com`)
      kind: Rule
      services:
        - name: frigate-ip-webhook
          port: 8080
