mqtt:
  enabled: true
  host: homeassistant.maas
  port: 1883
  user: frigate
  password: REDACTED_MQTT_PASSWORD
environment_vars:
  LIBVA_DRIVER_NAME: radeonsi
ffmpeg:
  hwaccel_args: preset-vaapi
go2rtc:
  streams:
    # tell go2rtc to pull JPEG HTTP, then re-encode to H264 via our preset
    mjpeg_cam: ffmpeg:http://admin:REDACTED_CAM1@192.168.1.220/videostream.cgi#video=h264#hardware
    reolink_doorbell: "rtsp://frigate:REDACTED_REOLINK@192.168.1.158:554/h264Preview_01_sub"
cameras:
  old_ip_camera:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/mjpeg_cam
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 640
      height: 480
      fps: 5  # Adjust for lower CPU usage
    objects:
      track:
        - person
        - car
    motion:
      threshold: 10  # Adjust sensitivity
      mask: 
        0.001,0.001,1,0.001,0.998,0.306,0.857,0.317,0.813,0.313,0.796,0.286,0.769,0.319,0.755,0.318,0.737,0.268,0.707,0.325,0.693,0.326,0.671,0.263,0.634,0.293,0.467,0.289,0.002,0.254
    zones: {}
    record:
      enabled: true
      retain:
        days: 5      # Number of days to keep recordings
        mode: motion # Options: all, motion, continuous
      events:
        retain:
          default: 10 # Retain event recordings for 10 days
  trendnet_ip_572w:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED_CAM2@192.168.1.107/play1.sdp
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1280
      height: 800
      fps: 5  # Adjust for lower CPU usage
    objects:
      track:
        - person
    motion:
      threshold: 30  # Adjust sensitivity
      contour_area: 10
      improve_contrast: 'true'
    zones: {}
    record:
      enabled: true
      retain:
        days: 5      # Number of days to keep recordings
        mode: motion # Options: all, motion, continuous
      events:
        retain:
          default: 10 # Retain event recordings for 10 days
  reolink_doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell
          roles:
            - detect
            - record
            - rtmp
    detect:
      width: 1920
      height: 1080
      fps: 5
    objects:
      track:
        - person
        - car
    motion:
      threshold: 25
      contour_area: 50
    zones: {}
    record:
      enabled: true
      retain:
        days: 7
        mode: motion
      events:
        retain:
          default: 14
detectors:
  coral:
    type: edgetpu
    device: usb
version: 0.14
