apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  # TODO: Move to separate Flux Kustomization with dependency on tailscale-operator HelmRelease
  # - connector.yaml  # CRDs installed by operator
  # NOTE: oauth-secret must be created manually:
  # kubectl create secret generic operator-oauth -n tailscale \
  #   --from-literal=client_id=YOUR_CLIENT_ID \
  #   --from-literal=client_secret=YOUR_CLIENT_SECRET
