apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets/operator-oauth.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  # TODO: Move to separate Flux Kustomization with dependency on tailscale-operator HelmRelease
  # - connector.yaml  # CRDs installed by operator
